---
os_distribution: manjaro

grub:
  params:
    - apparmor=1 
    - security=apparmor 
    - udev.log_priority=3
  theme: 
    path: /usr/share/grub/themes/manjaro/theme.txt

packages_blacklist:
  - gnome-shell-extension-arc-menu
  - gvfs-gphoto2
  - gvfs
  - gdm-plymouth
  - gnome-software
  - mutter-x11-sc
  - nautilus-typeahead
