---
# - - - - - - - - - - - - - - - - - - - - - - -
# BOOT

grub:
  enabled: False

plymouth:
  enabled: False

# - - - - - - - - - - - - - - - - - - - - - - -
# PACKAGES

packages:
  - AUDIO
  - DESKTOP_THEME
  - DESKTOP_UTILS
  - PRINTER
  - SHELL_EXTRA