---
# - - - - - - - - - - - - - - - - - - - - - - -
# PACKAGES

packages_categories:
  - DESKTOP_XFCE
  - DESKTOP_GTK_APPS

# - - - - - - - - - - - - - - - - - - - - - - -
# SERVICES

services:
  - name:  sddm.service
    enabled: no
    state: stopped
  - name:  gdm.service
    enabled: no
    state: stopped
  - name:  lightdm.service
    enabled: yes
    state: started
