---
- name: Set environment variables in /etc/environment
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: "^{{ item.name }}="
    line: "{{ item.name }}={{ item.value }}"
  with_items: "{{ environment_variables }}"