---
- name: Check hardware specifications
  block:
    - name: Check for Intel GPU
      raw: 'lspci | grep -i vga | grep -i intel'
      ignore_errors: yes
      register: gpu_intel

    - name: Check for AMD GPU
      raw: 'lspci | grep -i vga | grep -Ei "\Wamd|\Wati|advanced micro devices|radeon"'
      ignore_errors: yes
      register: gpu_amd

    - name: Check for NVidia GPU
      raw: 'lspci | grep -i vga | grep -Ei "\Wnvidia|\Wgeforce"'
      ignore_errors: yes
      register: gpu_nvidia

    - name: Check for Intel CPU
      raw: 'cat /proc/cpuinfo | grep vendor_id | grep -Ei "GenuineIntel|intel"'
      ignore_errors: yes
      register: cpu_intel
    
    - name: Check for AMD CPU
      raw: 'cat /proc/cpuinfo | grep vendor_id | grep -Ei "AuthenticAMD|amd"'
      ignore_errors: yes
      register: cpu_amd

    - name: Check for SSD Trim Support
      raw: 'hdparm -I /dev/sda | grep -i trim'
      ignore_errors: yes
      register: ssd_trim

- name: Install GPU drviers
  block:
    - name: Install Intel GPU Drivers
      pacman:
        name: "{{ video.drivers.intel }}"
        state: present
      when: gpu_intel.rc == 0
      become: yes

    - name: Install AMD GPU Drivers
      pacman:
        name: "{{ video.drivers.amd }}"
        state: present
      when: gpu_amd.rc == 0
      become: yes

    - name: Install NVidia GPU Drivers
      pacman:
        name: "{{ video.drivers.nvidia }}"
        state: present
      when: gpu_nvidia.rc == 0
      become: yes
  when: os_base == 'archlinux'

- name: Install GPU drviers
  block:
    - name: Install Intel GPU Drivers
      command: mhwd -a pci free 0300
      when: gpu_intel.rc == 0
      become: yes

    - name: Install AMD GPU Drivers
      command: mhwd -a pci free 0300
      when: gpu_amd.rc == 0
      become: yes

    - name: Install NVidia GPU Drivers
      command: mhwd -a pci nonfree 0300
      when: gpu_nvidia.rc == 0
      become: yes
  when: os_base == 'manjaro'

- name: Install CPU drviers
  block:
    - name: Install Intel Microcode
      pacman:
        name: intel-ucode
        state: present
      when: cpu_intel.rc == 0
      become: yes
    
    - name: Install AMD Microcode
      pacman:
        name: amd-ucode
        state: present
      when: cpu_amd.rc == 0
      become: yes

- name: Configure SSD Enhancements
  block:
    - name: Enable FS Trim timer
      service:
        name: fstrim.timer
        enabled: true
        state: started
      when: ssd_trim.rc == 0

- name: notify rebuild grub
  command: echo "rebuild grub"
  when: grub.enabled == True
  notify: rebuild grub
