---
# - - - - - - - - - - - - - - - - - - - - - - -
# SYSTEM

os_base: archlinux

#- - - - - - - - - - - - - - - - - - - - - - -
# KERNEL

kernel:
  packages:
    - linux
    - linux-headers

# - - - - - - - - - - - - - - - - - - - - - - -
# SUDOERS

sudo:
  nopasswd:
    - name: "%wheel"
      commands:
        - /usr/bin/makepkg
        - /usr/bin/pacman
        - /usr/bin/yay
    - name: yay
      commands:
        - /usr/bin/makepkg
        - /usr/bin/pacman
        - /usr/bin/yay

# - - - - - - - - - - - - - - - - - - - - - - -
# I18N & TIME

timesyncd:
  ntp_servers:
    - 0.arch.pool.ntp.org 
    - 1.arch.pool.ntp.org 
    - 2.arch.pool.ntp.org 
    - 3.arch.pool.ntp.org
  ntp_servers_fallback:
    - 0.pool.ntp.org 
    - 1.pool.ntp.org 
    - 0.fr.pool.ntp.org
  root_distance_max_sec: 5
  poll_interval_min_sec: 32
  poll_interval_max_sec: 2048

# - - - - - - - - - - - - - - - - - - - - - - -
# VIDEO DRIVERS

video:
  drivers:
    intel:
      - lib32-mesa
      - lib32-vulkan-icd-loader
      - lib32-vulkan-intel
      - vulkan-icd-loader
      - vulkan-intel
      - vulkan-intel
      - xf86-video-intel
    nvidia:
      - nvidia-lts
      - nvidia-utils
      - lib32-nvidia-utils
      - nvidia-settings
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    amd:
      - lib32-mesa
      - lib32-vulkan-icd-loader
      - lib32-vulkan-radeon
      - vulkan-icd-loader
      - vulkan-radeon
      - xf86-video-amdgpu

# - - - - - - - - - - - - - - - - - - - - - - -
# CPU

cpu:
  microcode:
    intel: intel-ucode
    amd: amd-ucode

# - - - - - - - - - - - - - - - - - - - - - - -
# NETWORK

hostname: "archlinux"

# - - - - - - - - - - - - - - - - - - - - - - -
# SERVICES

# Services are configured in the order in which they are listed here.
services:
  # Firewall
  - name: iptables.service
    enabled: yes
    state: restarted
  - name: ip6tables.service
    enabled: no
    state: stopped
  - name: sshguard.service
    enabled: yes
    state: restarted
  # Samba
  - name: smb.service
    enabled: yes
    state: started
  # SSH
  - name: sshd.service
    enabled: yes
    state: started
  # Hardware
  - name: acpid
    enabled: yes
    state: started
  - name: cpupower.service
    enabled: yes
    state: started
  # Bluetooth
  - name: bluetooth.service
    enabled: yes
    state: started
  - name: rfkill-block@bluetooth.service
    enabled: no
    state: stopped
  # Cron
  - name: cronie.service
    enabled: yes
    state: started
  # Pacman
  - name: mirrorlist-update.timer
    enabled: yes
    state: started
  - name: paccache.timer
    enabled: yes
    state: started

# - - - - - - - - - - - - - - - - - - - - - - -
# PACKAGES

# Specify known hosts for pacman / yay
packages_ssh_known_hosts: []
  # - "|1|REx/t/at9hf5s3fs6wWE9jqDpzQ=|h19BNpNqbsF4OW4lvseOGK/0qcE= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOZAVWmj2k+dHTfyum7FyIivGcVUkDFHaXmPNxDwF7l8TvkAN8VDQJHEEGJhALMYtNsQ+kt0gksSh4HZqj9n5hI="
  # - "|1|5UneA1GhAjeRXsbgcKcv+61zpn0=|cb3DK1OecmD+Y5mFPqdx5V80+xs= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM2DCBtPSTwWvBU3/3bAYwJVtnAmy+GEJf98Ek5QhOXh"

# pacman-key --recv-keys will be ran against the items in the list
packages_key_ids: []
  # - 50AAD02AEB1F61C9

# pacman-key --add will be ran against the items in the list
packages_key_files: []
  # - http://dl.foo.com/keyfile.key

# Dependencies to install before running the ansible playbook
# These packages can only be from the main arch repos
packages_initial_dependencies:
   - base-devel
   - binutils
   - git
   - python2
   - python-jmespath
   - openssh

packages_first:
  - reflector

# Packages which should never be installed. Used to blacklist packages from groups.
packages_blacklist: [] 


_CORE:
  - acl
  - acpid
  - cpupower
  - cronie
  - dhcpcd
  - git
  - gnupg
  - iptables
  - man-db
  - networkmanager
  - openssh
  - sshguard
  - stow
  - sudo

UTILS_GENERIC:
  - coreutils
  - dateutils
  - moreutils

UTILS_ARCHIVE:
  - bzip2
  - gzip
  - p7zip
  - unrar
  - unzip
  - zip
UTILS_DOCS:
  - pandoc

UTILS_FILE_SYSTEMS:
  - exfat-utils
  - ext4magic
  - fuse
  - ntfs-3g
  - samba
  - sshfs

UTILS_FILE_TRANSFER:
  - curl
  - lftp
  - rsync
  - wget
  - youtube-dl

UTILS_HARDWARE:
  - htop
  - glances
  - lshw
  - lsof

UTILS_MULTIMEDIA:
  - ffmpeg
  - graphicsmagick
  - imagemagick

UTILS_NETWORK:
  - dnsutils
  - iproute2
  - net-tools
  - nmap
  - openvpn
  - protonvpn-cli-ng
  - speedtest-cli
  - traceroute
  - whois

DEVELOPMENT:
  # javascript
  - nodejs
  - npm
  # c++
  - cmake
  - gcc
  - make
  - extra-cmake-modules
  # rust
  - rust
  # python
  - python
  - python-pip
  # mongodb
  - mongodb
  # sql
  - mariadb
  - mariadb-clients

VIRTUALIZATION:
  - docker
  - python-docker
  - vagrant
  - packer

AUDIO:
  - alsa-plugins
  - alsa-utils
  - pulseaudio
  - pulseaudio-bluetooth

AUDIO_PRO:    
  - a2jmidid
  - yabridge
  - yabridgectl

FONTS:
  - fontconfig
  - gsfonts
  - inter-font
  - nerd-fonts-fantasque-sans-mono
  - nerd-fonts-fira-code
  - tex-gyre-fonts
  - ttf-fantasque-sans-mono
  - ttf-fira-code
  - ttf-mac-fonts
  - ttf-ms-fonts

PRINTER:
  - cups
  - cups-pdf
  - epson-inkjet-printer-escpr
  - imagescan-plugin-networkscan
  - imagescan
  - ghostscript
  - gutenprint

PHONE:
  - libimobiledevice
  - ifuse

SHELL:
  # terminal
  - kitty
  # zsh
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  # shell extensions
  - neofetch
  - exa
  - starship-bin
  - w3m

SHELL_EXTRA:
  - bash-pipes
  - cava
  - cowsay
  - figlet
  - figlet-fonts
  - toilet
  - toilet-fonts
  - unimatrix-git
  - cmatrix

PACKAGE_MANAGERS:
  - snapd
  - flatpak

DESKTOP_XORG:
  - xorg

DESKTOP_THEME:
  - bibata-cursor-theme
  - pop-sound-theme-bin
  - papirus-icon-theme

DESKTOP_WM:
  - bspwm
  - sxhkd
  - dunst
  - picom-tryone-git
  - polybar
  - rofi
  - lxappearance

DESKTOP_UTILS:
  - dconf-editor
  - feh
  - python-pywal
  - ranger
  - scrot
  - xdg-user-dirs

DESKTOP_GNOME:
  # extras
  - gnome-tweaks
  - mousetweaks
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-arc-menu
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-dash-to-panel
  - gnome-shell-extension-pop-shell
  # display manager
  - gdm
  # gnome
  - gnome

DESKTOP_KDE:
  # extras
  - plasma-wayland-session
  - kdeconnect
  - kwin-lowlatency
  # display manager
  - sddm-kcm
  # plasma
  - plasma


  # - neovim
  # - robo3t-bin
  # - heidisql
  # - insomnia-bin