---
# - - - - - - - - - - - - - - - - - - - - - - -
# SYSTEM

os_base: ubuntu
os_version: focal

#- - - - - - - - - - - - - - - - - - - - - - -
# KERNEL

kernel_version: 5.8
kernel_subversion: 0-31
kernel_type: generic

kernel:
  packages:
    - linux-image-{{ kernel_version }}-{{ kernel_subversion }}-{{ kernel_type }}
    - linux-headers-{{ kernel_version }}-{{ kernel_subversion }}-{{ kernel_type }}
    - linux-tools-{{ kernel_version }}-{{ kernel_subversion }}-{{ kernel_type }}

# - - - - - - - - - - - - - - - - - - - - - - -
# SUDOERS

sudo:
  nopasswd:
    - name: "%wheel"
      commands:
        - /usr/bin/dpkg
        - /usr/bin/apt
        - /usr/bin/add-apt-repository

# - - - - - - - - - - - - - - - - - - - - - - -
# I18N & TIME

timesyncd:
  ntp_servers:
    - 0.ubuntu.pool.ntp.org 
    - 1.ubuntu.pool.ntp.org 
    - 2.ubuntu.pool.ntp.org 
    - 3.ubuntu.pool.ntp.org
  ntp_servers_fallback:
    - 0.pool.ntp.org 
    - 1.pool.ntp.org 
    - 0.fr.pool.ntp.org
  root_distance_max_sec: 5
  poll_interval_min_sec: 32
  poll_interval_max_sec: 2048

# - - - - - - - - - - - - - - - - - - - - - - -
# VIDEO DRIVERS

video:
  drivers:
    intel:
      - xserver-xorg-video-intel
      - libgl1-mesa-dri:i386
      - mesa-vulkan-drivers 
      - mesa-vulkan-drivers:i386
    nvidia:
      - xserver-xorg-video-nvidia-450
      - libvulkan1 
      - libvulkan1:i386
    amd:
      - xserver-xorg-video-amd-gpu
      - libgl1-mesa-dri:i386
      - mesa-vulkan-drivers 
      - mesa-vulkan-drivers:i386

# - - - - - - - - - - - - - - - - - - - - - - -
# CPU

cpu:
  microcode:
    intel: intel-microcode
    amd: amd64-microcode

# - - - - - - - - - - - - - - - - - - - - - - -
# PACKAGES

# sudo dpkg --add-architecture i386


packages_aptkey:
  asc:
    - url: https://www.mongodb.org/static/pgp/server-4.4.asc # mongodb
    - url: https://packages.microsoft.com/keys/microsoft.asc # vscode
    - url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc # brave
    - url: https://typora.io/linux/public-key.asc # typora
    - url: https://dl.winehq.org/wine-builds/winehq.key # wine
  keyserver:
    - key: 379CE192D401AB61 # balena etcher
      url: hkps://keyserver.ubuntu.com:443

packages_sources:
  - dest: /etc/apt/sources.list.d/mongodb-org-4.4.list
    contents: >-
      deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu {{ os_version }}/mongodb-org/4.4 multiverse
  - dest: /etc/apt/sources.list.d/vscode.list
    content: >-
      deb [arch=amd64] https://packages.microsoft.com/repos/vscode {{ os_version }} main
  - dest: /etc/apt/sources.list.d/brave-browser-release.list
    content: >-
      deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ {{ os_version }} main
  - dest: /etc/apt/sources.list.d/typora.list
    content: >-
      deb [arch=amd64] https://typora.io/linux {{ os_version }} main
  - dest: /etc/apt/sources.list.d/wine.list
    content: >-
      deb [arch=amd64] http://dl.winehq.org/wine-builds/ubuntu {{ os_version }} main
      
packages_ppa:
  - apandada1/foliate
  - graphics-drivers/ppa
  - kisak/kisak-mesa
  - lutris-team/lutris
  - nathan-renniewaldock/flux
  - nilarimogard/webupd8
  - oibaf/graphics-drivers

_CORE:
  - acl
  - acpid
  - cpufrequtils
  - cron
  - dhcpcd-common
  - dhcpcd5
  - git
  - gnupg
  - iptables-persistent
  - linux-tools-common
  - man-db
  - netfilter-persistent
  - network-manager
  - openssh-client
  - openssh-server 
  - sshguard
  - stow
  - sudo
  - apt-transport-https

UTILS_GENERIC:
  - coreutils
  - moreutils
  - dateutils

UTILS_ARCHIVE:
  - bzip2
  - gzip
  - p7zip-full
  - unrar
  - unzip
  - zip

UTILS_DOCS:
  - pandoc

UTILS_FILE_SYSTEMS:
  - exfat-utils
  - ext4magic
  - fuse
  - ntfs-3g
  - parted

UTILS_FILE_TRANSFER:
  - curl
  - lftp
  - rsync
  - wget
  - youtube-dl
  - samba

UTILS_HARDWARE:
  - htop
  - glances
  - lshw
  - lsof

UTILS_MULTIMEDIA:
  - ffmpeg
  - graphicsmagick
  - imagemagick
  
UTILS_NETWORK:
  - dnsutils
  - iproute2
  - net-tools
  - nmap
  - openvpn
  - protonvpn-cli
  - speedtest-cli
  - traceroute
  - whois

DEVELOPMENT:
  # javascript
  - nodejs
  - npm
  # c++
  - cmake
  - gcc
  - make
  - extra-cmake-modules
  # rust
  - rustc
  - cargo
  # python
  - python3
  - python3-pip
  # mongo
  - mongodb-org
  # sql
  - mariadb-client
  - mariadb-common
  - mariadb-server

VIRTUALIZATION:
  - docker
  - docker-compose
  - vagrant
  - packer

AUDIO:
  - alsa-utils
  - libasound2-plugins
  - libasound2-plugins-extra
  - pulseaudio
  - bluetooth

AUDIO_PRO:
  - a2jmidid

FONTS:
 - fontconfig
 - fontconfig-config
 - gsfonts
 - fonts-inter
 - fonts-fantasque-sans
 - fonts-firacode
 - fonts-texgyre
 - ttf-mscorefonts-installer

PRINTER:
  - cups
  - printer-driver-cups-pdf
  - printer-driver-escpr
  - printer-driver-gutenprint
  - simple-scan
  - ghostscript

PHONE:
  - ifuse
  - libimobiledevice6
  - libimobiledevice-utils

SHELL:
  # terminal
  - kitty
  # zsh
  - zsh
  - zsh-autosuggestions
  - zsh-common
  - zsh-syntax-highlighting
  # shell extensions
  - neofetch
  - exa
  - w3m

SHELL_EXTRA:
  - cava
  - cowsay
  - figlet
  - figlet-fonts
  - toilet
  - toilet-fonts
  - cmatrix

PACKAGE_MANAGERS:
  - snapd
  - flatpak

DESKTOP_XORG:
  - xserver-xorg

DESKTOP_THEME:
  - pop-sound-theme-bin
  - papirus-icon-theme

DESKTOP_WM:
  - bspwm
  - sxhkd
  - dunst
  - picom
  - polybar
  - rofi
  - lxappearance

DESKTOP_UTILS:
  - dconf-editor
  - feh
  - ranger
  - scrot
  - xdg-user-dirs

DESKTOP_GNOME:
  # extra
  - gnome-tweaks
  - mousetweaks
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-arc-menu
  - gnome-shell-extension-dashtodock
  - gnome-shell-extension-dash-to-panel
  # display manager
  - gdm3
  # gnome
  - vanilla-gnome-desktop

DESKTOP_KDE:
  # extra
  - kdeconnect
  - kwin-wayland-backend-wayland
  # display manager
  - kde-config-sddm
  - sddm
  # plasma
  - kde-plasma-desktop

DESKTOP_XFCE:
  # extras
  - xscreensaver
  - mugshot
  - fluxgui
  - gvfs
  - gvfs-backend
  - gvfs-common
  - gvfs-daemons
  # display manager
  - lightdm
  - lightdm-gtk-greeter-settings
  - lightdm-gtk-greeter
  # xfce
  - xfce4
  - xfce4-goodies

DESKTOP_APPS:
# audio
  - pavucontrol
# browsers
  - brave-browser
  - chromium-browser
  - firefox
# creative
  # - bitwig-studio # needs to be installed manually via deb file
  - blender
  - gimp
  - inkscape
  - musescore3
  - obs-studio
  - screenkey
# dev
  - code
  - zeal
# filesystems
  - woeusb
  - balena-etcher-electron
  - gparted
# media
  - handbrake
  - vlc
# network_admin
  - linssid
  - wireshark-qt
  - remmina
# network_files
  - filezilla
  - youtube-dlg
# office
  - foliate
  # - protonmail-bridge # probably complicated as fuck to install with apt
  - libreoffice
  - typora
# printer
  - system-config-printer
# social
  - discord # probably going to need to install a snap / flatpak
# virtualization
  - virtualbox

DESKTOP_GTK_APPS:
  # development
  - guake
  # archive
  - file-roller # gtk
  # creative
  - pitivi # gtk
  - olive-editor
  # filesystems
  - baobab # gtk
  # fonts
  - gnome-font-viewer # gtk
  - gnome-characters # gtk
  # hardware
  - gnome-logs # gtk
  - gnome-system-monitor # gtk
  - sysprof # gnome
  # media
  - gnome-screenshot # gtk
  - gthumb # gtk
  - quodlibet # gtk
  - parole # gtk
  # network_files
  - transmission-gtk # gtk
  # office
  - gnome-calculator # gtk
  - evince # gtk
  - thunderbird # gtk
  - simple-scan # gtk

DESKTOP_QT_APPS:
  # files
  - dolphin
  - dolphin-plugins
  - ark
  # system utils
  - kde-config-cron
  - qdirstat
  - ksystemlog
  - kfind  
  # development
  - kompare
  - kate
  - yakuake
  - konsole
  # creative
  - kwave
  - kolourpaint
  - kdenlive
  # network_files
  - kget
  - qbittorrent
  # office
  - kcalc
  - kmail
  - kalarm
  - korganizer
  - okular
  - print-manager
  # media
  - gwenview
  - juk

WINE:
  - winehq-staging
  - winetricks

GAMES:
  - xboxdrv
  - qjoypad
# steam
  - steam
# lutris
  - lutris
  - libasound2-plugins:i386
  - libdbus-1-3:i386
  - libfreetype6:i386
  - libgnutls30:i386
  - libgpg-error0:i386
  - libldap-2.4-2:i386
  - libsdl2-2.0-0:i386
  - libsqlite3-0:i386
  - libxml2:i386

MISC:
  - cpupower-gui

# - - - - - - - - - - - - - - - - - - - - - - -
# NOTES

# https://askubuntu.com/questions/1021748/set-cpu-governor-to-performance-in-18-04
# https://askubuntu.com/questions/1052919/iptables-reload-restart-on-ubuntu-18-04