# - - - - - - - - - - - - - - - - - - - - - - -
# SYSTEM

os_base: archlinux

# - - - - - - - - - - - - - - - - - - - - - - -
# USERS

users:
  - tag: main
    name: cameron
    fullname: "Cameron Sanders"
    email: csanders@protonmail.com
    shell: /usr/bin/zsh
    dotfiles: https://github.com/abstracted/_unixconf_dotfiles.git
    gnupg: 
      agent_browser_socket: True
      agent_socket: True
      agent_ssh_socket: True
      dirmngr_socket: True
    groups:
      - audio
      - docker
      - game
      - golang
      - lp
      - networkmanager
      - plugdev
      - printadmin
      - realtime
      - scanner
      - sshusers
      - syncthing
      - vboxusers
      - wheel
      - wireshark
    services: []

# - - - - - - - - - - - - - - - - - - - - - - -
# SUDOERS

sudo:
  nopasswd:
    - name: "%wheel"
      commands:
        - /usr/bin/ansible-playbook
        - /usr/bin/du
        - /usr/bin/find
        - /usr/bin/locate
        - /usr/bin/makepkg
        - /usr/bin/mount
        - /usr/bin/npm
        - /usr/bin/openvpn
        - /usr/bin/pacman
        - /usr/bin/reboot
        - /usr/bin/shutdown
        - /usr/bin/systemctl
        - /usr/bin/umount
        - /usr/bin/vim
        - /usr/bin/yay
    - name: yay
      commands:
        - /usr/bin/makepkg
        - /usr/bin/pacman
        - /usr/bin/yay

# - - - - - - - - - - - - - - - - - - - - - - -
# I18N & TIME

i18n:
  keymap: us
  timezone: America/Chicago
  locale: en_US.UTF-8
  localtime: True
  long: -96.796989
  lat: 32.776665

timesyncd:
  ntp_servers:
    - 0.arch.pool.ntp.org 
    - 1.arch.pool.ntp.org 
    - 2.arch.pool.ntp.org 
    - 3.arch.pool.ntp.org
  ntp_servers_fallback:
    - 0.pool.ntp.org 
    - 1.pool.ntp.org 
    - 0.fr.pool.ntp.org
  root_distance_max_sec: 5
  poll_interval_min_sec: 32
  poll_interval_max_sec: 2048

# - - - - - - - - - - - - - - - - - - - - - - -
# FONT

# TODO: This currently isn't used, maybe fix it ?

# font:
#   cursive: Ubuntu Italic
#   fantasy: New York Medium
#   monospace: Unbuntu Mono
#   sans_serif: Ubuntu Regular
#   serif: New York Medium

# - - - - - - - - - - - - - - - - - - - - - - -
# ENVIRONMENT VARIABLES

environment_variables: []

# - - - - - - - - - - - - - - - - - - - - - - -
# FILES

files:
  locked: [] # paths to files that will have  chattr +i applied to them

# - - - - - - - - - - - - - - - - - - - - - - -
# LIMITS

limits_conf:
  - domain: "*"
    type: soft
    item: nofile
    value: 16384
  - domain: "*"
    type: hard
    item: nofile
    value: 32768

# - - - - - - - - - - - - - - - - - - - - - - -
# FILESYSTEMS

fstab: []

# - - - - - - - - - - - - - - - - - - - - - - -
# BOOT

grub:
  enabled: True
  params:
    - iommu=soft
    - loglevel=3
    - consoleblank=60
    - threadirqs
    - udev.log_priority=3

mkinitcpio:
  hooks:
    - autodetect
    - base
    - block
    - filesystems
    - fsck
    - keyboard
    - keymap
    - modconf
    - resume
    - udev

plymouth:
  enabled: False

#- - - - - - - - - - - - - - - - - - - - - - -
# KERNEL

kernel:
  packages:
    - linux
    - linux-headers
  modules:
    - usb_storage
    - usbhid
    - xhci_pci
  sysctl:
    - name: "fs.inotify.max_user_watches"
      value: 524288

#- - - - - - - - - - - - - - - - - - - - - - -
# AUDIO

audio:
  sample_format: s24-32le
  sample_rate: 44100
  
jack:
  device: none
  capture: none
  playback: none
  periods: 2
  frames: 1024

# - - - - - - - - - - - - - - - - - - - - - - -
# VIDEO

video:
  drivers:
    intel:
      - lib32-mesa
      - lib32-vulkan-icd-loader
      - lib32-vulkan-intel
      - vulkan-icd-loader
      - vulkan-intel
      - vulkan-intel
      - xf86-video-intel
    nvidia:
      - nvidia-lts
      - nvidia-utils
      - lib32-nvidia-utils
      - nvidia-settings
      - vulkan-icd-loader
      - lib32-vulkan-icd-loader
    amd:
      - lib32-mesa
      - lib32-vulkan-icd-loader
      - lib32-vulkan-radeon
      - vulkan-icd-loader
      - vulkan-radeon
      - xf86-video-amdgpu

# - - - - - - - - - - - - - - - - - - - - - - -
# DOCKER

docker:
  enabled: True
  containers: []
  puid: 1000
  pgid: 1000
  storage_driver: overlay2
  storage_root: /var/lib/docker
  network:
    dockernet:
      name: dockernet
      driver: bridge
    default: # these are for the default docker "bridge" network
      name: bridge
      driver: bridge
      cidr: 24
      dns:
        - 174.138.21.128
      gateway: 172.17.0.1
      subnet: 172.17.0.0
      _subnet: 172.17.0. # used when assiging static ips for containers
      iptables: "false" # wether or not you want to allow docker to modify iptables

# - - - - - - - - - - - - - - - - - - - - - - -
# NETWORK

hostname: "archlinux"

# Static network configurations: 
# These can be used by services like dhcpcd for static routes / nameservers
# If no services which use these settings are enabled, they have no effect.
# Some services like NetworkManager may ignore some or all these settings.
network_conf:
  ip_address: 192.168.0.10
  cidr: 24
  subnet_mask: 255.255.255.0
  default_gateway: 192.168.0.1
  domain_name_servers: []

# DHCPCD configurations:
# Used as a lightweight network manager.
# Can also be used to set static network configurations when service is enabled.
dhcpcd:
  static: False

# NetworkManager configuration:
# Used mostly for desktop systems. 
# Servers should use dhcpcd.
network_manager:
  wifi:
    scan_rand_mac_address: 'yes'
    cloned_rand_mac_address: 'stable'
  ethernet:
    cloned_rand_mac_address: 'stable'
  manage_dns: True # enable or disable DNS to be managed via NetworkManager

# Iptables configuration:
firewall:
  # ports listed here will be opened via iptables
  ports:
    protonimap: 1143
    protonsmtp: 1025
    samba: 445
    ssh: 22

# - - - - - - - - - - - - - - - - - - - - - - -
# CRON JOBS

cron:
  jobs: []

# - - - - - - - - - - - - - - - - - - - - - - -
# SERVICES

# Services are configured in the order in which they are listed here.
services:
  # Firewall
  - name: iptables.service
    enabled: yes
    state: restarted
  - name: ip6tables.service
    enabled: no
    state: stopped
  - name: sshguard.service
    enabled: yes
    state: restarted
  # Samba
  - name: smb.service
    enabled: yes
    state: started
  # SSH
  - name: sshd.service
    enabled: yes
    state: started
  # Hardware
  - name: acpid
    enabled: yes
    state: started
  - name: cpupower.service
    enabled: yes
    state: started
  # Bluetooth
  - name: bluetooth.service
    enabled: yes
    state: started
  - name: rfkill-block@bluetooth.service
    enabled: no
    state: stopped
  # Cron
  - name: cronie.service
    enabled: yes
    state: started
  # SSD trim
  - name: fstrim.timer
    enabled: yes
    state: started
  # Network Time
  - name: systemd-timesyncd.service
    enabled: yes
    state: started
  # Pacman
  - name: mirrorlist-update.timer
    enabled: yes
    state: started
  - name: paccache.timer
    enabled: yes
    state: started
  # Misc
  - name: startup-custom.service
    enabled: yes
    state: started

# - - - - - - - - - - - - - - - - - - - - - - -
# PACKAGES

# Specify known hosts for pacman / yay
packages_ssh_known_hosts: []
  # - "|1|REx/t/at9hf5s3fs6wWE9jqDpzQ=|h19BNpNqbsF4OW4lvseOGK/0qcE= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOZAVWmj2k+dHTfyum7FyIivGcVUkDFHaXmPNxDwF7l8TvkAN8VDQJHEEGJhALMYtNsQ+kt0gksSh4HZqj9n5hI="
  # - "|1|5UneA1GhAjeRXsbgcKcv+61zpn0=|cb3DK1OecmD+Y5mFPqdx5V80+xs= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM2DCBtPSTwWvBU3/3bAYwJVtnAmy+GEJf98Ek5QhOXh"

# pacman-key --recv-keys will be ran against the items in the list
packages_key_ids: []
  # - 50AAD02AEB1F61C9

# pacman-key --add will be ran against the items in the list
packages_key_files: []
  # - http://dl.foo.com/keyfile.key

# Packages to install before other packages
packages_first: []


# Packages which should never be installed. Used to blacklist packages from groups.
packages_blacklist: [] 

# Packages to remove before installing or updating other packages
packages_remove: []

# Package sets from ./packages.yml
packages:
  - _CORE
  - FONTS
  - SHELL
  - UTILS
