

DESKTOP_XFCE:
  # extras
  - xscreensaver
  - mugshot
  - lightdm-gtk-greeter-settings
  - fluxgui
  - gvfs
  - gvfs-smb
  # display manager
  - lightdm
  - lightdm-gtk-greeter
  # xfce
  - xfce4
  - xfce4-goodies

DESKTOP_APPS:
# audio
  - pavucontrol
# browsers
  - chromium
  - firefox
# creative
  - bitwig-studio
  - blender
  - gimp
  - inkscape
  - musescore
  - obs-studio
  - screenkey
# dev
  - code
  - zeal
# filesystems
  - woeusb
  - etcher-bin
  - gparted
# media
  - handbrake
  - vlc
# network_admin
  - linssid
  - wireshark-qt
  - remmina
# network_files
  - filezilla
  - syncthing-gtk
  - youtube-dl-gui-git
# office
  - foliate
  - protonmail-bridge
  - libreoffice-fresh
  - marktext-bin
# package_managers
  - pamac
# printer
  - system-config-printer
# social
  - discord-canary
# virtualization
  - virtualbox

DESKTOP_GTK_APPS:
  # development
  - guake
  # archive
  - file-roller # gtk
  # creative
  - pitivi # gtk
  - olive
  # filesystems
  - baobab # gtk
  # fonts
  - gnome-font-viewer # gtk
  - gnome-characters # gtk
  # hardware
  - gnome-logs # gtk
  - gnome-system-monitor # gtk
  - sysprof # gnome
  # media
  - gnome-screenshot # gtk
  - gthumb # gtk
  - quodlibet # gtk
  - parole # gtk
  # network_files
  - transmission-gtk # gtk
  # office
  - gnome-calculator # gtk
  - evince # gtk
  - thunderbird # gtk
  - simple-scan # gtk

DESKTOP_QT_APPS:
  # files
  - dolphin
  - dolphin-plugins
  - ark
  # system utils
  - kcron
  - qdirstat
  - ksystemlog
  - kfind  
  # development
  - kompare
  - kate
  - yakuake
  - konsole
  # creative
  - kwave
  - kolourpaint
  - kdenlive
  # network_files
  - kget
  - qbittorrent
  # office
  - kcalc
  - kmail
  - kalarm
  - korganizer
  - okular
  - print-manager
  # media
  - gwenview
  - juk

WINE:
  - wine-staging
  - winetricks
  - wine-mono
  - protontricks

GAMES:
  - xboxdrv
  - qjoypad
# steam
  - steam
  - steam-fonts
# lutris
  - lutris
  - alsa-lib
  - alsa-plugins
  - giflib
  - gnutls
  - gst-plugins-base-libs
  - gtk3
  - lib32-alsa-lib
  - lib32-alsa-plugins
  - lib32-giflib
  - lib32-gnutls
  - lib32-gst-plugins-base-libs
  - lib32-gtk3
  - lib32-libgcrypt
  - lib32-libgpg-error
  - lib32-libjpeg-turbo
  - lib32-libldap
  - lib32-libpng
  - lib32-libpulse
  - lib32-libva
  - lib32-libxcomposite
  - lib32-libxinerama
  - lib32-libxslt
  - lib32-mpg123
  - lib32-ncurses
  - lib32-openal
  - lib32-opencl-icd-loader
  - lib32-sqlite
  - lib32-v4l-utils
  - lib32-vulkan-icd-loader
  - libgcrypt
  - libgpg-error
  - libjpeg-turbo
  - libldap
  - libpng
  - libpulse
  - libva
  - libxcomposite
  - libxinerama
  - libxslt
  - mpg123
  - ncurses
  - openal
  - opencl-icd-loader
  - sqlite
  - v4l-utils
  - vulkan-icd-loader
