_CORE:
  - acpid
  - cmake
  - cpupower
  - cronie
  - extra-cmake-modules
  - gcc
  - git
  - gnupg
  - make
# - man
  - man-db
  - openssh
  - stow
  - sudo
  - acl
  - sshguard

UTILS:
# _misc
  - coreutils
  - dateutils
  - moreutils
# archives
  - bzip2
  - gzip
  - p7zip
  - unrar
  - unzip
  - zip
# documents
  - pandoc
# file systems
  - exfat-utils
  - ext4magic
  - fuse
  - ntfs-3g
  - samba
  - sshfs
# file transfer
  - curl
  - lftp
  - rsync
  - wget
  - youtube-dl
# hardware
  - htop
  - glances
  - lshw
  - lsof
# multimedia
  - ffmpeg
  - graphicsmagick
  - imagemagick
# network admin
  - bind-tools
  - iproute2
  - net-tools
  - networkmanager
  - dhcpcd
  - nmap
  - openvpn
  - protonvpn-cli-ng
  - speedtest-cli
  - traceroute
  - whois

DEVELOPMENT:
  - neovim
  - nvm
  - robo3t-bin
  - heidisql
  - insomnia-bin
  - python
  - python-pip

VIRTUALIZATION:
  - docker
  - python-docker
  - vagrant
  - packer

AUDIO:
  - alsa-plugins
  - alsa-utils
  - pulseaudio
  - pulseaudio-bluetooth

AUDIO_PRO:    
  - a2jmidid
  - linvst

FONTS:
  - fontconfig
  - gsfonts
  - inter-font
  - nerd-fonts-fantasque-sans-mono
  - nerd-fonts-fira-code
  - tex-gyre-fonts
  - ttf-fantasque-sans-mono
  - ttf-fira-code
  - ttf-mac-fonts
  - ttf-ms-fonts

PRINTER:
  - cups
  - cups-pdf
  - epson-inkjet-printer-escpr
  - imagescan-plugin-networkscan
  - imagescan
  - ghostscript
  - gutenprint

PHONE:
  - libimobiledevice
  - ifuse
  - gvfs-afc
  - gvfs-gphoto2 

SHELL:
  # terminal
  - kitty
  # zsh
  - zsh
  - zsh-autosuggestions
  - zsh-completions
  - zsh-history-substring-search
  - zsh-syntax-highlighting
  # shell extensions
  - neofetch
  - exa
  - starship-bin
  - w3m

SHELL_EXTRA:
  - bash-pipes
  - cava
  - cowsay
  - figlet
  - figlet-fonts
  - toilet
  - toilet-fonts
  - unimatrix-git

DESKTOP_XORG:
  - xorg

DESKTOP_THEME:
  - bibata-cursor-theme
  - pop-sound-theme-bin
  - papirus-icon-theme

DESKTOP_WM:
  - bspwm
  - sxhkd
  - dunst
  - picom-tryone-git
  - polybar
  - rofi
  - lxappearance

DESKTOP_UTILS:
  - dconf-editor
  - feh
  - python-pywal
  - ranger
  - scrot
  - xdg-user-dirs

DESKTOP_GNOME:
  # extras
  - gnome-tweaks
  - mousetweaks
  - gnome-shell-extension-appindicator
  - gnome-shell-extension-arc-menu
  - gnome-shell-extension-dash-to-dock
  - gnome-shell-extension-dash-to-panel
  - gnome-shell-extension-pop-shell
  # display manager
  - gdm
  # gnome
  - gnome

DESKTOP_APPS:
# audio
  - pavucontrol
# browsers
  - chromium
  - firefox
# creative
  - bitwig-studio
  - blender
  - gimp
  - inkscape
  - musescore
  - obs-studio
  - screenkey
# dev
  - code
  - zeal
# filesystems
  - woeusb
  - etcher-bin
  - gparted
# media
  - handbrake
  - vlc
# network_admin
  - linssid
  - wireshark-qt
  - remmina
# network_files
  - filezilla
  - syncthing-gtk
  - youtube-dl-gui-git
# office
  - foliate
  - protonmail-bridge
  - libreoffice-fresh
  - marktext-bin
# package_managers
  - pamac
# printer
  - system-config-printer
# social
  - discord-canary
# virtualization
  - virtualbox

DESKTOP_GTK_APPS:
  # development
  - guake
  # archive
  - file-roller # gtk
  # creative
  - pitivi # gtk
  - olive
  # filesystems
  - baobab # gtk
  # fonts
  - gnome-font-viewer # gtk
  - gnome-characters # gtk
  # hardware
  - gnome-logs # gtk
  - gnome-system-monitor # gtk
  - sysprof # gnome
  # media
  - gnome-screenshot # gtk
  - gthumb # gtk
  - quodlibet # gtk
  - parole # gtk
  # network_files
  - transmission-gtk # gtk
  # office
  - gnome-calculator # gtk
  - evince # gtk
  - thunderbird # gtk
  - simple-scan # gtk

WINE:
  - wine-staging
  - winetricks
  - wine-mono
  - protontricks

GAMES:
  - xboxdrv
  - qjoypad
# steam
  - steam
  - steam-fonts
# lutris
  - lutris-git
  - alsa-lib
  - alsa-plugins
  - giflib
  - gnutls
  - gst-plugins-base-libs
  - gtk3
  - lib32-alsa-lib
  - lib32-alsa-plugins
  - lib32-giflib
  - lib32-gnutls
  - lib32-gst-plugins-base-libs
  - lib32-gtk3
  - lib32-libgcrypt
  - lib32-libgpg-error
  - lib32-libjpeg-turbo
  - lib32-libldap
  - lib32-libpng
  - lib32-libpulse
  - lib32-libva
  - lib32-libxcomposite
  - lib32-libxinerama
  - lib32-libxslt
  - lib32-mpg123
  - lib32-ncurses
  - lib32-openal
  - lib32-opencl-icd-loader
  - lib32-sqlite
  - lib32-v4l-utils
  - lib32-vulkan-icd-loader
  - libgcrypt
  - libgpg-error
  - libjpeg-turbo
  - libldap
  - libpng
  - libpulse
  - libva
  - libxcomposite
  - libxinerama
  - libxslt
  - mpg123
  - ncurses
  - openal
  - opencl-icd-loader
  - sqlite
  - v4l-utils
  - vulkan-icd-loader
