---
# - - - - - - - - - - - - - - - - - - - - - - -
# NETWORK

hostname: "workstation"

# - - - - - - - - - - - - - - - - - - - - - - -
# PACKAGES

packages:
  - AUDIO_PRO
  - GAMES

# - - - - - - - - - - - - - - - - - - - - - - -
# BOOT

grub:
  params:
    - resume=UUID=f629bf7b-cb2d-45a0-a870-e14f32a3a620

filesystem_external_opts:
  - "defaults"
  - "nofail"
  - "noatime"

fstab:
  - src: "/dev/disk/by-label/Storage"
    path: "/mnt/Storage"
    fstype: "ntfs"
    state: "mounted"
    opts: "{{ filesystem_external_opts }}"

