---
- name: "Reload the systemd daemon" 
  command: systemctl daemon-reload

- name: Setup services defined in services
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  become: yes
  with_items: "{{ services }}"
  ignore_errors: yes
  when: services is defined

- name: Disable services defined in services_remove
  systemd:
    name: "{{ item.name }}"
    enabled: no
    state: stopped
  become: yes
  with_items: "{{ services_remove }}"
  ignore_errors: yes
  when: services_remove is defined