---
- name: "Reload the systemd daemon" 
  command: systemctl daemon-reload

- name: Setup services defined in services
  systemd:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
    state: "{{ item.state }}"
  become: yes
  with_items: "{{ services }}"
  ignore_errors: yes
  when: services is defined

- name: Disable services defined in services_remove
  systemd:
    name: "{{ item.name }}"
    enabled: no
    state: stopped
  become: yes
  with_items: "{{ services_remove }}"
  ignore_errors: yes
  when: services_remove is defined

# - name: Enable System systemd services from templates directory /etc/systemd/system/
#   systemd:
#     name: '{{ item.path | basename | regex_replace("\.j2","") }}'
#     enabled: yes
#     state: started
#   become: yes
#   with_filetree: '../templates/'
#   when: item.state == 'file' and item.path | regex_search("systemd/system/.*(service|timer)")
#   ignore_errors: yes