---
- name: Update pacman cache
  command: "pacman -Sy"
  become: yes

- name: Create a list of already installed pacman packages
  raw: "pacman -Qq"
  become: yes
  register: pacman_packages_installed

- name: Create a list of already installed pacman groups
  raw: "pacman -Qg | awk '{print $1}' | uniq"
  become: yes
  register: pacman_groups_installed

- name: Create a list of already installed pacman aur packages
  command: "pacman -Qqm"
  become: yes
  ignore_errors: yes
  register: pacman_aur_installed

- name: Merge list of already installed packages
  set_fact:
    packages_installed: >
      {{ pacman_packages_installed.stdout_lines + 
      pacman_groups_installed.stdout_lines + 
      pacman_aur_installed.stdout_lines }}

- name: Install base dependencies
  command: "pacman -S --noconfirm {{ item }}"
  become: yes
  with_items: "{{ packages_initial_dependencies }}"
  when: item not in packages_installed

- name: Link jmespath for ansible line-in-file module
  command: "[ -e /usr/bin/jmespath ] || ln -sf `which jp.py` /usr/bin/jmespath"
  ignore_errors: yes
  become: yes