---
- name: Uninstall packages specified in packages_remove
  command: "sudo pacman -Rns {{ item }}"
  with_items: "{{ packages_remove }}"
  become: yes
  ignore_errors: yes
  when: packages_remove | length > 0

- name: Upgrade the system
  pacman:
    update_cache: yes
    upgrade: yes
    state: present
  become: yes

- name: Install pacakges
  yay:
    update_cache: no
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_first + (packages | sort) }}"
  when: >
    item not in packages_installed and
    item not in packages_blacklist
  become: yes
  become_user: yay