---
# - - - - - - - - - - - - - - - - - - - - - - -
# SYSTEM

os_distribution: ubuntu
os_version: focal

#- - - - - - - - - - - - - - - - - - - - - - -
# KERNEL

kernel_version: 5.8
kernel_subversion: 0-44
kernel_type: generic

kernel:
  packages:
    - linux-image-{{ kernel_version }}.{{ kernel_subversion }}-{{ kernel_type }}
    - linux-headers-{{ kernel_version }}.{{ kernel_subversion }}-{{ kernel_type }}
    - linux-tools-{{ kernel_version }}.{{ kernel_subversion }}-{{ kernel_type }}

# - - - - - - - - - - - - - - - - - - - - - - -
# SUDOERS

sudo:
  nopasswd:
    - name: "%wheel"
      commands:
        - /usr/bin/dpkg
        - /usr/bin/apt
        - /usr/bin/add-apt-repository

# - - - - - - - - - - - - - - - - - - - - - - -
# I18N & TIME

timesyncd:
  ntp_servers:
    - 0.ubuntu.pool.ntp.org 
    - 1.ubuntu.pool.ntp.org 
    - 2.ubuntu.pool.ntp.org 
    - 3.ubuntu.pool.ntp.org
  ntp_servers_fallback:
    - 0.pool.ntp.org 
    - 1.pool.ntp.org 
    - 0.fr.pool.ntp.org
  root_distance_max_sec: 5
  poll_interval_min_sec: 32
  poll_interval_max_sec: 2048

# - - - - - - - - - - - - - - - - - - - - - - -
# VIDEO DRIVERS

video:
  drivers:
    intel:
      - xserver-xorg-video-intel
      - libgl1-mesa-dri:i386
      - mesa-vulkan-drivers 
      - mesa-vulkan-drivers:i386
    nvidia:
      - xserver-xorg-video-nvidia-450
      - libvulkan1 
      - libvulkan1:i386
    amd:
      - xserver-xorg-video-amd-gpu
      - libgl1-mesa-dri:i386
      - mesa-vulkan-drivers 
      - mesa-vulkan-drivers:i386

# - - - - - - - - - - - - - - - - - - - - - - -
# CPU

cpu:
  microcode:
    intel: intel-microcode
    amd: amd64-microcode

# - - - - - - - - - - - - - - - - - - - - - - -
# PACKAGES

packages_initial_dependencies: 
  - stow

packages_first: []
packages_remove: []
packages_blacklist: []

packages_aptkey:
  asc:
    - url: https://www.mongodb.org/static/pgp/server-4.4.asc # mongodb
    - url: https://packages.microsoft.com/keys/microsoft.asc # vscode
    - url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc # brave
    - url: https://typora.io/linux/public-key.asc # typora
    - url: https://dl.winehq.org/wine-builds/winehq.key # wine
  keyserver:
    - id: 379CE192D401AB61 # balena etcher
      url: keyserver.ubuntu.com

packages_repository:
  source:
    - name: mongodb-org-4.4
      content: >-
        deb [arch=amd64,arm64] https://repo.mongodb.org/apt/ubuntu {{ os_version }}/mongodb-org/4.4 multiverse
    - name: vscode
      content: >-
        deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    - name: brave-browser-release
      content: >-
        deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main
    - name: typora
      content: >-
        deb [arch=amd64] https://typora.io/linux ./
    - name: wine.list
      content: >-
        deb [arch=amd64] http://dl.winehq.org/wine-builds/ubuntu {{ os_version }} main
  ppa:
    - apandada1/foliate
    - graphics-drivers/ppa
    - kisak/kisak-mesa
    - lutris-team/lutris
    - nilarimogard/webupd8
    - oibaf/graphics-drivers

# - - - - - - - - - - - - - - - - - - - - - - -
# NOTES

# https://askubuntu.com/questions/1021748/set-cpu-governor-to-performance-in-18-04
# https://askubuntu.com/questions/1052919/iptables-reload-restart-on-ubuntu-18-04